# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='web.Tag'),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='status',
            field=models.IntegerField(choices=[(0, '绝不考虑'), (1, '短期内不考虑'), (2, '已在其它机构报名'), (3, '近期内报名'), (4, '已报名'), (5, '已试听')]),
        ),
    ]
